### PR TITLE
Allow laravel 5.1 installs by lowering the symfony/process requirement

### PR DESCRIPTION
**Pull request by jhoopes**
Change composer.json file to lower the symfony process requirement to allow installation on 5.1

### CODE REVIEW

**Comment by Modelizer** [comment]
@jhoopes take a fork and then propose a PR. That will be better :)

**Comment by Modelizer** [comment]
@jhoopes also let me know what are you planning next?

I'm thinking to add windows support with chrome... Right now working on it.

**Comment by jhoopes** [comment]
This is actually still broken... 

Composer doesn't seem to like the \* in the version constraint.  so >=2.7 would actually be the best constraint.  not sure if you want to do it, or have me fork and make another PR.

Should we make a wiki page or use issues for road mapping?  

What I'm thinking of next is pulling in some of the structural things for a 'readable' API with.  This would likely be better in a wiki page, but what I'm thinking is going with the traits that I had in my repository, but maybe in the future we separate it out more.

Also, are you sure we'd like to put the selenium config inside of the .env file?

The other options I had were actually just having people use the already existing phpunit.xml file to add additional environment variables.  That way things like DB connection and other things are already set there and not in 2 different places.

**Comment by Modelizer** [comment]
Use Issue for road mapping.

Yes, I suggest you first start integrating API, regarding traits that depend on the scenario. If we think using trait is the best option then will do so.

Yes, I'm sure to use selenium config from .env file... Regarding Database connection, if a user wants to explicitly connect to different DB he needs to do it via phpunit.xml file.

**Pull request merged**
